### ISSUE TITLE
Make requirements/deps work with pip>=19.2.0

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden#4585]
If pip>=19.2.0 is installed, `deps` will fail with the following error:
```
Compiling requirements.in. Error!

Traceback (most recent call last):
  File "/home/hack/work/brainbot/pyvenv3-dev/bin/pip-compile", line 10, in <module>
    sys.exit(cli())
  File "/home/hack/work/brainbot/pyvenv3-dev/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hack/work/brainbot/pyvenv3-dev/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hack/work/brainbot/pyvenv3-dev/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hack/work/brainbot/pyvenv3-dev/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hack/work/brainbot/pyvenv3-dev/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hack/work/brainbot/pyvenv3-dev/lib/python3.7/site-packages/piptools/scripts/compile.py", line 256, in cli
    repository = PyPIRepository(pip_options, session, build_isolation)
  File "/home/hack/work/brainbot/pyvenv3-dev/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 95, in __init__
    self.finder = PackageFinder(**finder_kwargs)
TypeError: __init__() got an unexpected keyword argument 'find_links'

Traceback (most recent call last):
  File "../tools/pip-compile-wrapper.py", line 321, in <module>
    main()
  File "../tools/pip-compile-wrapper.py", line 307, in main
    compile_source(verbose=parsed.verbose, dry_run=parsed.dry_run)
  File "../tools/pip-compile-wrapper.py", line 246, in compile_source
    _run_pip_compile(source_name, upgrade_all=upgrade_all, verbose=verbose, dry_run=dry_run)
  File "../tools/pip-compile-wrapper.py", line 146, in _run_pip_compile
    process.check_returncode()
  File "/usr/lib64/python3.7/subprocess.py", line 428, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '['/home/hack/work/brainbot/pyvenv3-dev/bin/pip-compile', '--quiet', '--no-index', '--output-file', '/home/hack/work/brainbot/raiden/requirements/requirements.txt', '/home/hack/work/brainbot/raiden/requirements/requirements.in']' returned non-zero exit status 1.
```

**Comment by karlb** [comment]
Worked for me after upgrading both pip and pip-tools. If this works for others, too, we can revert https://github.com/raiden-network/raiden/commit/c6e7ecc94dde02c834dfa1b0ef7c698105f4a5c6 and close this.

**Comment by palango** [comment]
@karlb I still get the error with the latest versions:
```sh
± % pip list | grep pip
apipkg                    1.5
pip                       19.3.1
pip-tools                 4.3.0
```

Error:
```
% requirements/deps upgrade mypy
Upgrading package(s):
  - mypy
Compiling requirements-dev.in. Error!

Command errored out with exit status 1:
 command: /Users/paul/Work/raiden/venv/bin/python3 /Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/gz/0f_3f9k96gd1hblwgd1r8h280000gn/T/tmp5j1awpcd
     cwd: /var/folders/gz/0f_3f9k96gd1hblwgd1r8h280000gn/T/tmpall6gi7fbuild/matrix-synapse
Complete output (10 lines):
Traceback (most recent call last):
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
    main()
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 101, in prepare_metadata_for_build_wheel
    backend = _build_backend()
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 76, in _build_backend
    obj = getattr(obj, path_part)
AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
----------------------------------------
Traceback (most recent call last):
  File "/Users/paul/Work/raiden/venv/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/piptools/scripts/compile.py", line 359, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/piptools/resolver.py", line 168, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/piptools/resolver.py", line 263, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/piptools/resolver.py", line 358, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/piptools/repositories/local.py", line 70, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 269, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 225, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_internal/distributions/source/legacy.py", line 39, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 563, in prepare_metadata
    self.metadata_directory = metadata_generator(self)
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_internal/operations/generate_metadata.py", line 136, in _generate_metadata
    return install_req.prepare_pep517_metadata()
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 607, in prepare_pep517_metadata
    metadata_dir
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 170, in prepare_metadata_for_build_wheel
    '_allow_fallback': _allow_fallback,
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 248, in _call_hook
    extra_environ=extra_environ
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 275, in runner
    spinner=spinner,
  File "/Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /Users/paul/Work/raiden/venv/bin/python3 /Users/paul/Work/raiden/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/gz/0f_3f9k96gd1hblwgd1r8h280000gn/T/tmp5j1awpcd Check the logs for full command output.

Traceback (most recent call last):
  File "../tools/pip-compile-wrapper.py", line 321, in <module>
    main()
  File "../tools/pip-compile-wrapper.py", line 317, in main
    upgrade_source(packages, verbose=parsed.verbose, dry_run=parsed.dry_run)
  File "../tools/pip-compile-wrapper.py", line 276, in upgrade_source
    source_name, upgrade_packages=package_names, verbose=verbose, dry_run=dry_run
  File "../tools/pip-compile-wrapper.py", line 146, in _run_pip_compile
    process.check_returncode()
  File "/Users/paul/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 428, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '['/Users/paul/Work/raiden/venv/bin/pip-compile', '--quiet', '--no-index', '--upgrade-package', 'mypy', '--output-file', '/Users/paul/Work/raiden/requirements/requirements-dev.txt', '/Users/paul/Work/raiden/requirements/requirements-dev.in']' returned non-zero exit status 1.

**Comment by karlb** [comment]
Current hypothesis: works on Linux, fails on Mac.
